### PR TITLE
setup.sh: Update XLink Kai Installation Process

### PR DESCRIPTION
**Pull request by MasonT8198**

### CODE REVIEW

**Comment by CrunchBite** [comment]
TeamXLink will have a followup PR to this one to change the Kai launch script and further improve the installation process

**Comment by MasonT8198** [comment]
There this should be complete, thanks @CrunchBite

**Comment by MasonT8198** [comment]
added the forgotten sudo so no more infinite loops, however the repo issue is still present, will be fixed internally by us :p

**Comment by MasonT8198** [comment]
@toolboc?

**Pull request merged**
